### PR TITLE
Client done

### PR DESCRIPTION
**Pull request by ryan-shaw**
@LukeCS is the client done?

### CODE REVIEW

**Comment by ryanshawty** [comment]
@LukeCS oh no tests... make sure you add tests and edit the build matrix before merging this branch.

**Comment by LukeCS** [comment]
I tried committing with some changes and some testing but I came across a problem.

**Comment by ryanshawty** [comment]
@LukeCS what problem?

**Comment by ryanshawty** [comment]
5 new defect(s) introduced to ryanshawty/G53SQM found with Coverity Scan.


New defect(s) Reported-by: Coverity Scan
Showing 5 of 5 defect(s)


** CID 101964:  Dereference null return value  (NULL_RETURNS)
/src/vc/min/chat/Client/Client.java: 339 in vc.min.chat.Client.Client$RemoteReader.run()()
/src/vc/min/chat/Client/Client.java: 331 in vc.min.chat.Client.Client$RemoteReader.run()()
/src/vc/min/chat/Client/Client.java: 350 in vc.min.chat.Client.Client$RemoteReader.run()()

** CID 101965:  SIC: Inner class could be made static  (FB.SIC_INNER_SHOULD_BE_STATIC)
/src/vc/min/chat/Client/Client.java: 275 in ()

** CID 101966:  DLS: Dead local store  (FB.DLS_DEAD_LOCAL_STORE)
/src/vc/min/chat/Client/Client.java: 236 in vc.min.chat.Client.Client$SendPMHandler.actionPerformed(java.awt.event.ActionEvent)()

** CID 101967:  UrF: Unread field  (FB.URF_UNREAD_FIELD)
/src/vc/min/chat/Client/Client.java: 73 in ()

** CID 101968:  DLS: Dead local store  (FB.DLS_DEAD_LOCAL_STORE)
/src/vc/min/chat/Client/Client.java: 216 in vc.min.chat.Client.Client$SendClientsHandler.actionPerformed(java.awt.event.ActionEvent)()


________________________________________________________________________________________________________
*** CID 101964:  Dereference null return value  (NULL_RETURNS)
/src/vc/min/chat/Client/Client.java: 339 in vc.min.chat.Client.Client$RemoteReader.run()()
333
334                                        // System.out.println("Got a message");
335                                         break;
336                                case 4:
337
338                                             Packet4ListClients packet1 = (Packet4ListClients) packet;
>>>     CID 101964:  Dereference null return value  (NULL_RETURNS)
>>>     Accessing field of null object "packet1".
339                                             clients = packet1.clients;
340
341                                             for (int i = 0; i < clients.size(); i++) {
342                                                     output.append((i+1) + " " + clients.get(i) + "\n");
343                                             }
344
/src/vc/min/chat/Client/Client.java: 331 in vc.min.chat.Client.Client$RemoteReader.run()()
325                                             break;
326                                case 2:
327                                         //System.out.println("Keep-Alive");
328                                             break;
329                                case 3:
330                                         Packet3Message packet3 = (Packet3Message) packet;
>>>     CID 101964:  Dereference null return value  (NULL_RETURNS)
>>>     Accessing field of null object "packet3".
331                                         output.append(packet3.from + "\n");
332                                         output.append(packet3.message + "\n");
333
334                                        // System.out.println("Got a message");
335                                         break;
336                                case 4:
/src/vc/min/chat/Client/Client.java: 350 in vc.min.chat.Client.Client$RemoteReader.run()()
344
345                                         System.out.println("List Clients");
346                                             break;
347                                case 5:
348
349                                             Packet5PM packet5pm = (Packet5PM) packet;
>>>     CID 101964:  Dereference null return value  (NULL_RETURNS)
>>>     Accessing field of null object "packet5pm".
350                                             output.append(packet5pm.fromUsername + " -> " + packet5pm.toUsername + "\n" + packet5pm.message + "\n");
351                                         //System.out.println("Personal Message");
352                                             break;
353                        }
354                     }
355                 } catch (Exception e) {

________________________________________________________________________________________________________
*** CID 101965:  SIC: Inner class could be made static  (FB.SIC_INNER_SHOULD_BE_STATIC)
/src/vc/min/chat/Client/Client.java: 275 in ()
269                     aboutDialog = new AboutDialog(frame, "About", true);
270                 }
271                 aboutDialog.setVisible(true);
272             }
273         }
274
>>>     CID 101965:  SIC: Inner class could be made static  (FB.SIC_INNER_SHOULD_BE_STATIC)
>>>     Should vc.min.chat.Client.Client$AboutDialog be a _static_ inner class?
275         private class AboutDialog extends JDialog implements ActionListener  {
276             public AboutDialog(Frame parent, String title, boolean modal) {
277                 super(parent,title,modal);
278                 add(new JLabel("The ChatClient is a neat tool that allows you to talk " +
279                         "to other ChatClients via a ChatServer"),BorderLayout.NORTH);
280                 JButton b = new JButton("OK");

________________________________________________________________________________________________________
*** CID 101966:  DLS: Dead local store  (FB.DLS_DEAD_LOCAL_STORE)
/src/vc/min/chat/Client/Client.java: 236 in vc.min.chat.Client.Client$SendPMHandler.actionPerformed(java.awt.event.ActionEvent)()
230
231         private class SendPMHandler implements ActionListener {
232             public void actionPerformed(ActionEvent e) {
233                 String text = input2.getText();
234                 String name = inputPM.getText();
235                 //text = usernames.getSelectedItem() + ": " + text + "\n";
>>>     CID 101966:  DLS: Dead local store  (FB.DLS_DEAD_LOCAL_STORE)
>>>     Dead store to packet4listclients.
236                 Packet4ListClients packet4listclients = new Packet4ListClients(true);
237
238                 Packet5PM packet5pm = new Packet5PM(name, currentName, text);
239                 try {
240                     packetHandler.writePacket(packet5pm);
241                 } catch(IOException e1) {

________________________________________________________________________________________________________
*** CID 101967:  UrF: Unread field  (FB.URF_UNREAD_FIELD)
/src/vc/min/chat/Client/Client.java: 73 in ()
67      private boolean running;
68
69      private PacketHandler packetHandler;
70
71      private ArrayList<String> clients;
72         public Client() {
>>>     CID 101967:  UrF: Unread field  (FB.URF_UNREAD_FIELD)
>>>     Unread field: vc.min.chat.Client.Client.text.
73              text = new JLabel();
74             output = new JTextArea(10,50);
75             scrollPane = new JScrollPane(output,
76                     ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
77                     ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
78             input = new JTextField(50);

________________________________________________________________________________________________________
*** CID 101968:  DLS: Dead local store  (FB.DLS_DEAD_LOCAL_STORE)
/src/vc/min/chat/Client/Client.java: 216 in vc.min.chat.Client.Client$SendClientsHandler.actionPerformed(java.awt.event.ActionEvent)()
210                 input2.setText("");
211             }
212         }
213
214         private class SendClientsHandler implements ActionListener {
215             public void actionPerformed(ActionEvent e) {
>>>     CID 101968:  DLS: Dead local store  (FB.DLS_DEAD_LOCAL_STORE)
>>>     Dead store to text.
216                 String text = input2.getText();
217                 //text = usernames.getSelectedItem() + ": " + text + "\n";
218                 Packet4ListClients packet4listclients = new Packet4ListClients(true);
219
220                 try {
221                     packetHandler.writePacket(packet4listclients);

**Pull request merged**
